### ISSUE TITLE
Not able to connect to IOT EdgeHub on TLS - Remote host closed connection during handshake

### ISSUE THREAD

**Issue by solankigithub** [Azure/iotedge#159]
I am trying to connect to my edge gateway from Java program:
Below is the program:

```
import javax.net.SocketFactory;
import javax.net.ssl.SSLContext;

import org.eclipse.paho.client.mqttv3.MqttClient;
import org.eclipse.paho.client.mqttv3.MqttConnectOptions;
import org.eclipse.paho.client.mqttv3.MqttException;
import org.eclipse.paho.client.mqttv3.MqttMessage;
import org.eclipse.paho.client.mqttv3.persist.MemoryPersistence;


public class Client {

	public static void main(String args[]) {
		String topic        = "hello/world";
        String content      = "Message from MqttPublishSample";
        int qos             = 2;
        String broker       = "ssl://192.168.1.104:8883";
        String clientId     = "JavaSample";
        MemoryPersistence persistence = new MemoryPersistence();

        try {
        	System.setProperty("https.protocols", "TLSv1,TLSv1.1,TLSv1.2");
        	MqttClient sampleClient = new MqttClient(broker, clientId, persistence);
            MqttConnectOptions connOpts = new MqttConnectOptions();
            connOpts.setCleanSession(true);
            String caCertFile = "C:\\Users\\ssandee5\\Desktop\\certs\\azure-iot-test-only.root.ca.cert.pem";
            String clientCrtFilePath ="C:\\Users\\ssandee5\\Desktop\\certs\\new-edge-device-full-chain.cert.pem";
            String clientKeyFilepath = "C:\\Users\\ssandee5\\Desktop\\certs\\new-edge-device.key.pem";
            SocketFactory socketFactory = SslUtil.getSocketFactory(caCertFile, clientCrtFilePath, clientKeyFilepath, "1234");             
            connOpts.setSocketFactory(socketFactory);
            
            System.out.println("Connecting to broker: "+broker);
            sampleClient.connect(connOpts);
            System.out.println("Connected");
            System.out.println("Publishing message: "+content);
            MqttMessage message = new MqttMessage(content.getBytes());
            message.setQos(qos);
            sampleClient.publish(topic, message);
            System.out.println("Message published");
            sampleClient.disconnect();
            System.out.println("Disconnected");
            System.exit(0);
        } catch(MqttException me) {
            System.out.println("reason "+me.getReasonCode());
            System.out.println("msg "+me.getMessage());
            System.out.println("loc "+me.getLocalizedMessage());
            System.out.println("cause "+me.getCause());
            System.out.println("excep "+me);
            me.printStackTrace();
        }
	}
	
}

```

Get below error:
```

[2018-08-15 13:47:40 +00:00]: Starting Edge Hub
[08/15/2018 01:47:40.998 PM] Edge Hub Main()
2018-08-15 13:47:47.881 +00:00 [INF] - Starting Edge Hub
2018-08-15 13:47:47.951 +00:00 [INF] - Version - 1.0.0.14487025 (52ef77db24126bf473265fc09c53d35290a2dd6b)
2018-08-15 13:47:47.953 +00:00 [INF] - 
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

2018-08-15 13:47:47.953 +00:00 [INF] - Installing intermediate certificates.
2018-08-15 13:47:48.437 +00:00 [INF] - Attempting to connect to IoT Hub for client myrasberrypi/$edgeHub via AMQP...
2018-08-15 13:47:48.742 +00:00 [INF] - Connected to IoT Hub for client myrasberrypi/$edgeHub via AMQP, with client operation timeout 60000.
2018-08-15 13:47:48.779 +00:00 [INF] - Created cloud connection for client myrasberrypi/$edgeHub
2018-08-15 13:47:48.786 +00:00 [INF] - New cloud connection created for device myrasberrypi/$edgeHub
2018-08-15 13:47:48.821 +00:00 [INF] - Initializing configuration
2018-08-15 13:47:50.540 +00:00 [INF] - Created persistent store at /tmp/edgeHub
2018-08-15 13:47:50.741 +00:00 [INF] - Created new message store
2018-08-15 13:47:50.744 +00:00 [INF] - Started task to cleanup processed and stale messages
2018-08-15 13:47:51.060 +00:00 [INF] - New device connection for device myrasberrypi/$edgeHub
2018-08-15 13:47:58.179 +00:00 [INF] - Entering connected state
2018-08-15 13:48:01.227 +00:00 [INF] - Obtained edge hub config from module twin
2018-08-15 13:48:01.933 +00:00 [INF] - Set the following 1 route(s) in edge hub
2018-08-15 13:48:01.940 +00:00 [INF] - route: FROM /* INTO $upstream
2018-08-15 13:48:01.953 +00:00 [INF] - Updated message store TTL to 7200 seconds
2018-08-15 13:48:01.955 +00:00 [INF] - Updated the edge hub store and forward configuration
2018-08-15 13:48:01.957 +00:00 [INF] - Initialized edge hub configuration
2018-08-15 13:48:02.443 +00:00 [INF] - Starting protocol heads - (HTTP, MQTT, AMQP)
2018-08-15 13:48:02.459 +00:00 [INF] - Starting HTTP head
2018-08-15 13:48:03.014 +00:00 [INF] - User profile is available. Using '"/home/edgehubuser/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest.
2018-08-15 13:48:03.177 +00:00 [INF] - Creating key {a4d2e43e-7b44-488e-a236-ac58b46eb53e} with creation date 2018-08-15 13:48:03Z, activation date 2018-08-15 13:48:03Z, and expiration date 2018-11-13 13:48:03Z.
2018-08-15 13:48:03.246 +00:00 [WRN] - No XML encryptor configured. Key {a4d2e43e-7b44-488e-a236-ac58b46eb53e} may be persisted to storage in unencrypted form.
2018-08-15 13:48:03.271 +00:00 [INF] - Writing data to file '"/home/edgehubuser/.aspnet/DataProtection-Keys/key-a4d2e43e-7b44-488e-a236-ac58b46eb53e.xml"'.
2018-08-15 13:48:05.035 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
2018-08-15 13:48:05.166 +00:00 [INF] - Started HTTP head
2018-08-15 13:48:05.191 +00:00 [INF] - Starting MQTT head
2018-08-15 13:48:05.814 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
2018-08-15 13:48:06.143 +00:00 [INF] - Starting AMQP head
2018-08-15 13:48:06.185 +00:00 [INF] - Started MQTT head
2018-08-15 13:48:06.802 +00:00 [INF] - Started AMQP head
2018-08-15 13:54:27.903 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 57410699
2018-08-15 13:54:28.011 +00:00 [WRN] - TLS handshake failed., System.AggregateException: One or more errors occurred. (Authentication failed, see inner exception.) ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__50_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__50_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---
, 234238c1
2018-08-15 13:55:03.349 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 32bca4b2
2018-08-15 13:55:03.558 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 11949434
2018-08-15 13:55:14.797 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 6d644826
2018-08-15 13:55:15.005 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 7ef30397
2018-08-15 13:55:48.355 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 40ea8e49
2018-08-15 13:55:48.563 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 107e77d4
2018-08-15 13:57:39.568 +00:00 [WRN] - TLS handshake failed., System.AggregateException: One or more errors occurred. (Authentication failed, see inner exception.) ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__50_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__50_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---
, 7a159400
2018-08-15 13:57:39.569 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 5542b962
2018-08-15 13:57:50.754 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 6710d977
2018-08-15 13:57:50.971 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 0fea78b2
2018-08-15 13:59:00.902 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 56985a7f
2018-08-15 13:59:01.115 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 627da9db
2018-08-15 13:59:33.042 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 71af2654
2018-08-15 13:59:33.249 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 36e1f5c9
2018-08-15 14:05:02.633 +00:00 [WRN] - TLS handshake failed., System.AggregateException: One or more errors occurred. (Authentication failed, see inner exception.) ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__50_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__50_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---
, 2b1debb4
2018-08-15 14:05:02.842 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 2cee1732
2018-08-15 14:05:35.483 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 5a00131d
2018-08-15 14:05:35.692 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 39aed1a0

```

**Comment by myagley** [comment]
Hello. Thanks for the issue report.

Where is the `caCertFile` generated from? In order for this to work, this CA certificate chain needs to be the same chain that the Edge Hub's server certificate was generated from.

There are also a couple of other things to note:
* The Edge Hub does not currently support mutual TLS or cert based authentication. It only support SAS token authentication
* The Edge Hub is not a general purpose MQTT broker. There are a defined set of MQTT topics that are supported. More info here: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support
* The Edge Hub (and Azure IoT Hub) does not support QoS level 2. Only QoS 0 and 1 are supported.

You may want to look at using the Azure IoT Hub java SDK, as many of these issues are handled for you. @timtay-microsoft do you have any java examples for IoT Edge java modules?

**Comment by solankigithub** [comment]
Thanks for the response, i am using below link to generate the certificates:
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway-linux

This certificates were generated on Rasberry Pi - Linux which i am using as field gateway.

My requirement is very simple, i have leaf devices that are running on ESP8266 and connected to field gateway. I want to filter some data on the gateway by deploying a module on the field gateway.

I would like to know how can i proceed to fulfill this requirement.

Connecting from a java client to my edge gateway is just to explore how the edge connectivity works. 
At end, i have to fulfill the above mentioned requirement.
Any kind of direction would be highly appreciated.

-Sandeep

**Comment by ts4iot** [comment]
Hi @solankigithub - you have to add the certificate from:
/var/lib/iotedge/hsm/certs/edge_owner_ca*.pem of your gateway to the trust store of your java client. 

You can do this with:

```
String ca = "content of your cert";
DeviceClientConfig dcc = client.getConfig();
IotHubAuthenticationProvider ap = dcc.getAuthenticationProvider();
ap.setIotHubTrustedCert(ca);
```

The description from https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway-linux also cost me hours and days. It looks like, V2 always uses the self-generated certificates from directory /var/lib/iotedge/hsm/certs/ and ignores the configuration in /etc/iotedge/config.yaml

This is only a workaround. A better description of how to configure the certificates for transparent mode would be desirable.

**Comment by myagley** [comment]
@ts4iot this is a bug and is fixed on master. We are planning a release for next week which will include the fix. 

We are also working on more in depth documentation for how to set up the certificates. It should be published soon.

**Comment by solankigithub** [comment]
@ts4iot  I tried executing my code as you suggested.


Below is my java code:

```
import com.microsoft.azure.sdk.iot.device.*;
import com.microsoft.azure.sdk.iot.device.auth.IotHubAuthenticationProvider;
import com.microsoft.azure.sdk.iot.device.*;
import com.microsoft.azure.sdk.iot.device.transport.IotHubConnectionStatus;

import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.List;


/** Sends a number of event messages to an IoT Hub. */
public class IOTJavaClient
{
    private  static final int D2C_MESSAGE_TIMEOUT = 2000; // 2 seconds
    private  static List failedMessageListOnClose = new ArrayList(); // List of messages that failed on close

    protected static class EventCallback implements IotHubEventCallback
    {
        public void execute(IotHubStatusCode status, Object context)
        {
            Message msg = (Message) context;

            System.out.println("IoT Hub responded to message "+ msg.getMessageId()  + " with status " + status.name());

            if (status==IotHubStatusCode.MESSAGE_CANCELLED_ONCLOSE)
            {
                failedMessageListOnClose.add(msg.getMessageId());
            }
        }
    }

    protected static class IotHubConnectionStatusChangeCallbackLogger implements IotHubConnectionStatusChangeCallback
    {
        @Override
        public void execute(IotHubConnectionStatus status, IotHubConnectionStatusChangeReason statusChangeReason, Throwable throwable, Object callbackContext)
        {
            System.out.println();
            System.out.println("CONNECTION STATUS UPDATE: " + status);
            System.out.println("CONNECTION STATUS REASON: " + statusChangeReason);
            System.out.println("CONNECTION STATUS THROWABLE: " + (throwable == null ? "null" : throwable.getMessage()));
            System.out.println();

            if (throwable != null)
            {
                throwable.printStackTrace();
            }

            if (status == IotHubConnectionStatus.DISCONNECTED)
            {
                //connection was lost, and is not being re-established. Look at provided exception for
                // how to resolve this issue. Cannot send messages until this issue is resolved, and you manually
                // re-open the device client
            }
            else if (status == IotHubConnectionStatus.DISCONNECTED_RETRYING)
            {
                //connection was lost, but is being re-established. Can still send messages, but they won't
                // be sent until the connection is re-established
            }
            else if (status == IotHubConnectionStatus.CONNECTED)
            {
                //Connection was successfully re-established. Can send messages.
            }
        }
    }

    /**
     * Sends a number of messages to an IoT Hub. Default protocol is to 
     * use MQTT transport.
     *
     * @param args
     * args[0] = IoT Hub connection string
     * args[1] = number of requests to send
     * args[2] = protocol (optional, one of 'mqtt' or 'amqps' or 'https' or 'amqps_ws')
     * args[3] = path to certificate to enable one-way authentication over ssl for amqps (optional, default shall be used if unspecified).
     */
    public static void main(String[] args)
            throws IOException, URISyntaxException
    {
        System.out.println("Starting...");
        System.out.println("Beginning setup.");

       
        String connString = "HostName=TankeyHub.azure-devices.net;DeviceId=myrasberrypi;SharedAccessKey=DXHqn4Oqy0qhabQ5ZUQ65MqaDIvDg+**********=;GatewayHostName=192.168.43.158";
        int numRequests= 2;
        String pathToCertificate = null;
        
        IotHubClientProtocol protocol;
        protocol = IotHubClientProtocol.MQTT;
        
        //pathToCertificate = "C:\\Users\\ssandee5\\Eclipse\\workspace\\AzureIOTGradle\\src\\main\\java\\edge_owner_ca.cert.pem";
        
        
        System.out.println("Successfully read input parameters.");
        System.out.format("Using communication protocol %s.\n", protocol.name());

        DeviceClient client = new DeviceClient(connString, protocol);
        
        DeviceClientConfig dcc = client.getConfig();
        IotHubAuthenticationProvider ap = dcc.getAuthenticationProvider();
        ap.setIotHubTrustedCert(Cert.certificate);
        
        
        if (pathToCertificate != null )
        {
            client.setOption("SetCertificatePath", pathToCertificate );
        }

        System.out.println("Successfully created an IoT Hub client.");

        // Set your token expiry time limit here
        //long time = 2400;
        //client.setOption("SetSASTokenExpiryTime", time);
        //System.out.println("Updated token expiry time to " + time);

        client.registerConnectionStatusChangeCallback(new IotHubConnectionStatusChangeCallbackLogger(), new Object());

        client.open();

        System.out.println("Opened connection to IoT Hub.");
        System.out.println("Sending the following event messages:");

        String deviceId = "myrasberrypi";
        double temperature = 0.0;
        double humidity = 0.0;

        for (int i = 0; i < numRequests; ++i)
        {
            temperature = 20 + Math.random() * 10;
            humidity = 30 + Math.random() * 20;

            String msgStr = "{\"deviceId\":\"" + deviceId +"\",\"messageId\":" + i + ",\"temperature\":"+ temperature +",\"humidity\":"+ humidity +"}";

            try
            {
                Message msg = new Message(msgStr);
                msg.setProperty("temperatureAlert", temperature > 28 ? "true" : "false");
                msg.setMessageId(java.util.UUID.randomUUID().toString());
                msg.setExpiryTime(D2C_MESSAGE_TIMEOUT);
                System.out.println(msgStr);

                EventCallback callback = new EventCallback();
                client.sendEventAsync(msg, callback, msg);
            }

            catch (Exception e)
            {
                e.printStackTrace(); // Trace the exception
            }
        }

        System.out.println("Wait for " + D2C_MESSAGE_TIMEOUT / 1000 + " second(s) for response from the IoT Hub...");

        // Wait for IoT Hub to respond.
        try
        {
            Thread.sleep(D2C_MESSAGE_TIMEOUT);
        }

        catch (InterruptedException e)
        {
            e.printStackTrace();
        }

        // close the connection
        System.out.println("Closing");
        client.closeNow();

        if (!failedMessageListOnClose.isEmpty())
        {
            System.out.println("List of messages that were cancelled on close:" + failedMessageListOnClose.toString());
        }

        System.out.println("Shutting down...");
    }
}

```
I get below exception:

```
Starting...
Beginning setup.
Successfully read input parameters.
Using communication protocol MQTT.
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
Successfully created an IoT Hub client.
Exception in thread "main" java.io.IOException: Could not open the connection
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:164)
	at com.microsoft.azure.sdk.iot.device.InternalClient.open(InternalClient.java:130)
	at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:317)
	at IOTJavaClient.main(IOTJavaClient.java:118)
Caused by: com.microsoft.azure.sdk.iot.device.exceptions.TransportException: java.io.IOException: java.security.cert.CertificateException: java.io.IOException: Incomplete data
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:202)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:641)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:277)
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:160)
	... 3 more
Caused by: java.io.IOException: java.security.cert.CertificateException: java.io.IOException: Incomplete data
	at com.microsoft.azure.sdk.iot.device.auth.IotHubAuthenticationProvider.getSSLContext(IotHubAuthenticationProvider.java:50)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:123)
	... 6 more
Caused by: java.security.cert.CertificateException: java.io.IOException: Incomplete data
	at sun.security.provider.X509Factory.engineGenerateCertificates(Unknown Source)
	at java.security.cert.CertificateFactory.generateCertificates(Unknown Source)
	at com.microsoft.azure.sdk.iot.deps.auth.IotHubCertificateManager.getCertificateCollection(IotHubCertificateManager.java:150)
	at com.microsoft.azure.sdk.iot.deps.auth.IotHubSSLContext.generateTrustManagerFactory(IotHubSSLContext.java:259)
	at com.microsoft.azure.sdk.iot.deps.auth.IotHubSSLContext.generateDefaultSSLContext(IotHubSSLContext.java:235)
	at com.microsoft.azure.sdk.iot.deps.auth.IotHubSSLContext.<init>(IotHubSSLContext.java:106)
	at com.microsoft.azure.sdk.iot.device.auth.IotHubAuthenticationProvider.generateSSLContext(IotHubAuthenticationProvider.java:164)
	at com.microsoft.azure.sdk.iot.device.auth.IotHubAuthenticationProvider.getSSLContext(IotHubAuthenticationProvider.java:40)
	... 7 more
Caused by: java.io.IOException: Incomplete data
	at sun.security.provider.X509Factory.readOneBlock(Unknown Source)
	at sun.security.provider.X509Factory.parseX509orPKCS7Cert(Unknown Source)
	... 15 more

```

May be i am doing something wrong ??

Thanks !

**Comment by mrohera** [comment]
For the value in the GatewayHostName field in the connection string of the downstream device, can you use the same value that you would have specified in the config.yaml under hostname? Also please use specify the value in lower case.

**Comment by solankigithub** [comment]
Thanks for feedback, i tried followed your instruction. Below is my code:

```
public static void main(String[] args)
            throws IOException, URISyntaxException
    {
        System.out.println("Starting...");
        System.out.println("Beginning setup.");
        
        System.setProperty("https.protocols", "TLSv1,TLSv1.1,TLSv1.2");
        
        String connString = "HostName=TankeyHub.azure-devices.net;DeviceId=tankey-device;SharedAccessKey=7GhTKVbUg/Jy35UI/lcarfHA+5QbzVk3HJGdGlyqwWQ=;GatewayHostName=rasberrypi";
        IotHubClientProtocol protocol;
        protocol = IotHubClientProtocol.MQTT;

        File file = new File("C:\\Users\\ssandee5\\Eclipse\\workspace\\AzureIOTGradle\\src\\main\\java\\edge_owner_cav0cQJsrFHjxosiOJDer2oKf-O45ZXKVJrO5WFWtFKe0_.cert.pem");
        FileInputStream fin = new FileInputStream(file);
        String ca = convertStreamToString(fin);
        System.out.println(ca);
        
        System.out.format("Using communication protocol %s.\n", protocol.name());

        DeviceClient client = new DeviceClient(connString, protocol);
        
        DeviceClientConfig dcc = client.getConfig();
        IotHubAuthenticationProvider ap = dcc.getAuthenticationProvider();
        ap.setIotHubTrustedCert(ca);

        System.out.println("Successfully created an IoT Hub client.");

        client.registerConnectionStatusChangeCallback(new IotHubConnectionStatusChangeCallbackLogger(), new Object());

        client.open();

        System.out.println("Opened connection to IoT Hub.");

        try
        {
            Thread.sleep(5000);
        }

        catch (InterruptedException e)
        {
            e.printStackTrace();
        }

        // close the connection
        System.out.println("Closing");
        client.closeNow();
		
        System.out.println("Shutting down...");
    }



	private static String convertStreamToString(FileInputStream fin) {
		// TODO Auto-generated method stub
		StringBuilder sb = new StringBuilder();
	    try {
	    	Reader r = new InputStreamReader(fin, "UTF-8");  //or whatever encoding
		    int ch = r.read();
		    while(ch >= 0) {
		        sb.append((char)ch);
		        ch = r.read();
		    }
	    }
	    catch(Exception ex) {
	    	
	    }
		
	    return sb.toString();
	}
    
```

It still throws below error message:

```
Starting...
Beginning setup.
-----BEGIN CERTIFICATE-----
MIIEzjCCAragAwIBAgIEa4tFZzANBgkqhkiG9w0BAQsFADAdMRswGQYDVQQDDBJU
ZXN0IEVkZ2UgT3duZXIgQ0EwHhcNMTgwODE1MTIzMDMyWhcNMTgxMTEzMTIzMDMy
WjAdMRswGQYDVQQDDBJUZXN0IEVkZ2UgT3duZXIgQ0EwggIiMA0GCSqGSIb3DQEB
AQUAA4ICDwAwggIKAoICAQDHKOELDBtmtwZoTJa44LHjIAcZJ3ONQbRbKrVf7XkW
GKLaFx/EasIS2JRJYTizt8ViEz3oz92X9/z7SOHfbeQKl8LVexENXphVZNfqNAFU
KsbbM6F8tPiNaRy1GWW2c/v4Akm/B/46CjqnZLRvQBz1TMnSeUzpUoK6zIe7KI6G
WTOCKJ1XSeatrLxrC1mLMa2J/XJkNaCwiLdjLCC/NjR5Mx2WLzEJAxJ2uZVwBT8x
Qh7awbBNPWPDR4ncQQbOVsGMzFH3hwCFHtHwy7eNqVJBm91oD1PFu3Msj09u3SyH
RKH098xL5n4b/jw6FVWXljsxnkJyNNcpH7KH5LQ52UIFHvjrghoYTbqAhC8WWL2X
L/1/XWsbEtLHbX5sjd1kbP+DKd3cGOz9aqmRTnVXS9x71ijoQx0YOaQwHjgn8G2x
uHGnjJKQdmMFA9ilDdhlr28flPTkYhu8e5iJBMneqkZ3PKKyfc/Co8dyy2CYeYfs
+nU6KFXwp3BQfM0uizPEPASD+XbPwoR3WNbJfpcjdg5AIaURY59IX9opJuOh7oxy
t5NqMvx1OogN80xgnoF5X6rqSBBvYa7mAIkEcYB1iuP5hRiRy3PFJBUe7JnTUD53
jsBLtjc9MYRL6RGuj/6og4HpxcnpbT12AF0AaQvRyyT1hM2l5gjCMvCMTprmH0AZ
nwIDAQABoxYwFDASBgNVHRMBAf8ECDAGAQEBAgEDMA0GCSqGSIb3DQEBCwUAA4IC
AQBecprjkc4j5d6Fdx7foNHKQqbDAgZMicgXKozdr/toS04+blDj1iZvM92YM3g+
e6UGIuIYGlw200lFTPZf68O3Or0wGtqb72bZuWCUchzLfzwpUkJaK2Qxiyr56pRf
2cXO8udsuWVFVnRxVeolrWRm/E0yoFGVw5p8SJS8jpcqaYyz5hg0Kpi3Zv64uT5X
aRTrshFdkaWEFitAbD2CITSFsj5bcdDveSfcvO+nGs9tAEyLcDAaLcLgGsPKwgsT
fOnn6LjhfiIPK/y3lcKMRMM1+ZCYdgTgenuPjsKVh4MVKhahu9ADABiqhey3WDrY
0lIOd+BdgBG/ecoANMIK/Ai+TPUc1Vw1L9JjR6r20eGU+Zz8oW7wK9mcyKhSCKki
DcM5zgHQddNzuwOaTqGRyAETj6UZXpn/85RdbQSTtPgkjT7WNobY+zhrRklplER+
WUhTl/HaKmyqID1dGLyKZ9hfpPeZ/fUyg2F+Daji8iIjtO+WolXvNBUqoLJ2NbJH
DiHxyZtgBVj+Li4jeeCyO+7fVrvqrno/9JAXlKvhE4LQhH7LUmDvVSg2MZebZOAQ
+VHZcK4PkmSfN40SKV90wdvZj5bQwsVlPeKKKNWkeewDoo61qPsmEIxNt+wx+u++
EXI1lsKYUj7lWSfhRais/w265RutbqlV+wTmBTRYM7tiPQ==
-----END CERTIFICATE-----

Using communication protocol MQTT.
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
Successfully created an IoT Hub client.
Exception in thread "main" java.io.IOException: Could not open the connection
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:164)
	at com.microsoft.azure.sdk.iot.device.InternalClient.open(InternalClient.java:130)
	at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:317)
	at IOTJavaClient.main(IOTJavaClient.java:103)
Caused by: com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Unable to establish MQTT connection
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:47)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connect(Mqtt.java:116)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.start(MqttMessaging.java:52)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:179)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:641)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:277)
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:160)
	... 3 more
Caused by: MqttException (0) - javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:715)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:108)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:701)
	... 7 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(Unknown Source)
	... 13 more

```

I copied the file from my linux(Rasbian) folder : /var/lib/iotedge/hsm/certs

Any help?

**Comment by solankigithub** [comment]
Ok so it worked now. The issue was that the edgeHub was give OutOfMemory Exception.
I set the environment variable "OptimizeForPerformance" to false. After that i was able to connect to the Azure EdgeHub.

May i ask how can i read the messages in a module to filter the messages received from leaf device?
Can you please help ?

**Comment by solankigithub** [comment]
ok, i am to read messages by setting the routes as 

```
"routes": {
          "NodeJSModuleToIoTHub": "FROM /messages/modules/NodeJSModule/outputs/* INTO $upstream",
          "sensorToNodeJSModule": "FROM /* INTO BrokeredEndpoint(\"/modules/NodeJSModule/inputs/input1\")"
        }

```
Thanks a ton !!!!

Azure IOT rocks !! 👍
