### ISSUE TITLE
EdgeHub loses connection to IoTHub every 20-30m

### ISSUE THREAD

**Issue by somme89** [Azure/iotedge#1801]
We have several identical Linux x64 based devices running IoTEdge without problems. However, in one case the EdgeHub loses connection to our IoTHub every 20m-30m. It takes up to 10m before it reconnects. This pattern is repeated 24/7. 

We have tried running different versions of EdgeHub include release candidates with no effect. The internet connection is good and the connection to the IoTHub seems to be fine when testing with the following command:

sudo docker exec -it edgeHub nc -vz xxxxxx-iot-hub.azure-devices.net 5671

Here's the start and end of the EdgeHub module log from where it starts failing to where it reconnects again:

```
<6> 2019-10-03 14:20:39.067 +00:00 [INF] - Reauthenticating connected clients
<6> 2019-10-03 14:25:38.718 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
<6> 2019-10-03 14:25:38.771 +00:00 [INF] - Cleaned up 11 messages from queue for endpoint iothub and 11 messages from message store.
<6> 2019-10-03 14:25:39.064 +00:00 [INF] - Reauthenticating connected clients
<6> 2019-10-03 14:26:47.127 +00:00 [INF] - Exiting connected state
<6> 2019-10-03 14:26:47.127 +00:00 [INF] - Entering unreachable state
<4> 2019-10-03 14:26:47.130 +00:00 [WRN] - Error calling IotHub for connectivity test
Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: The operation has timed out. ---> System.TimeoutException: The operation has timed out.
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.RoundTripTwinMessage(AmqpMessage amqpMessage, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.SendTwinPatchAsync(TwinCollection reportedProperties, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.SendTwinPatchAsync(TwinCollection reportedProperties, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass25_0.<<SendTwinPatchAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendTwinPatchAsync(TwinCollection reportedProperties, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.UpdateReportedPropertiesAsync(TwinCollection reportedProperties)
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.<>c__DisplayClass30_0.<<InvokeFunc>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 184
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 144
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 172
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.UpdateReportedPropertiesAsync(IMessage reportedPropertiesMessage) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 171
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.UpdateReportedPropertiesAsync(IMessage reportedPropertiesMessage) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 177
   at Microsoft.Azure.Devices.Edge.Hub.Core.Cloud.RetryingCloudProxy.<>c__DisplayClass22_0.<<ExecuteOperation>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/cloud/RetryingCloudProxy.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.Core.Cloud.RetryingCloudProxy.ExecuteOperation[T](Func`2 func, String operation) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/cloud/RetryingCloudProxy.cs:line 71
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceConnectivityManager.ConnectivityChecker.Check() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/DeviceConnectivityManager.cs:line 208
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceConnectivityManager.CheckConnectivity() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/DeviceConnectivityManager.cs:line 171
<6> 2019-10-03 14:27:14.266 +00:00 [INF] - Entering disconnected state
<6> 2019-10-03 14:27:14.267 +00:00 [INF] - Cloud connection for 208000000096973/$edgeHub is False
<6> 2019-10-03 14:27:14.267 +00:00 [INF] - Connection status for 208000000096973/$edgeHub changed to Disconnected
<6> 2019-10-03 14:27:14.300 +00:00 [INF] - Cloud connection for 208000000096973/distriwin-proxy is False
<6> 2019-10-03 14:27:14.300 +00:00 [INF] - Connection status for 208000000096973/distriwin-proxy changed to Disconnected
<6> 2019-10-03 14:27:14.301 +00:00 [INF] - Retrying cloud proxy operation SendMessageAsync for 208000000096973/distriwin-proxy.
Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry. ---> System.TimeoutException: The operation did not complete within the allocated time 00:01:00 for object message.
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.SendingAmqpLink.EndSendMessage(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpLinkHelper.SendAmqpMessageAsync(SendingAmqpLink sendingAmqpLink, AmqpMessage message, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpUnit.SendMessageAsync(AmqpMessage message, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpUnit.SendEventAsync(AmqpMessage message, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass14_0.<<SendEventAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(Message message)
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.<>c__DisplayClass30_0.<<InvokeFunc>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 184
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 144
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 172
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.SendMessageAsync(IMessage inputMessage) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 134
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.SendMessageAsync(IMessage inputMessage) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 140
   at Microsoft.Azure.Devices.Edge.Hub.Core.Cloud.RetryingCloudProxy.<>c__DisplayClass22_0.<<ExecuteOperation>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/cloud/RetryingCloudProxy.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.Core.Cloud.RetryingCloudProxy.ExecuteOperation[T](Func`2 func, String operation) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/cloud/RetryingCloudProxy.cs:line 71
<6> 2019-10-03 14:27:14.306 +00:00 [INF] - Attempting to connect to IoT Hub for client 208000000096973/distriwin-proxy via AMQP...
<6> 2019-10-03 14:28:14.298 +00:00 [INF] - Closing receiver in cloud proxy 829c0725-1f5c-4df8-9127-6654d63c1f30 for 208000000096973/$edgeHub
.....
...
...
Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 184
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 144
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.InvokeFunc[T](Func`1 func, String operation, Boolean useForConnectivityCheck) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 172
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ConnectivityAwareClient.OpenAsync() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClient.cs:line 62
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.ConnectToIoTHub(ITokenProvider newTokenProvider) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 127
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.CreateNewCloudProxyAsync(ITokenProvider newTokenProvider) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 102
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnection.Create(IIdentity identity, Action`2 connectionStatusChangedHandler, ITransportSettings[] transportSettings, IMessageConverterProvider messageConverterProvider, IClientProvider clientProvider, ICloudListener cloudListener, ITokenProvider tokenProvider, TimeSpan idleTimeout, Boolean closeOnIdleTimeout, TimeSpan operationTimeout, String productInfo) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs:line 91
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnectionProvider.<>c__DisplayClass16_1.<<Connect>b__2>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnectionProvider.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudConnectionProvider.Connect(IIdentity identity, Action`2 connectionStatusChangedHandler) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnectionProvider.cs:line 133
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Edge.Hub.Core.Cloud.RetryingCloudProxy.GetCloudProxy() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/cloud/RetryingCloudProxy.cs:line 101
   at Microsoft.Azure.Devices.Edge.Hub.Core.Cloud.RetryingCloudProxy.ExecuteOperation[T](Func`2 func, String operation) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/cloud/RetryingCloudProxy.cs:line 68
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceConnectivityManager.ConnectivityChecker.Check() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/DeviceConnectivityManager.cs:line 208
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceConnectivityManager.CheckConnectivity() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/DeviceConnectivityManager.cs:line 171
<6> 2019-10-03 14:32:47.934 +00:00 [INF] - Attempting to connect to IoT Hub for client 208000000096973/distriwin-proxy via AMQP...
<6> 2019-10-03 14:32:51.702 +00:00 [INF] - Exiting disconnected state
<6> 2019-10-03 14:32:51.702 +00:00 [INF] - Received device connected callback
<6> 2019-10-03 14:32:51.703 +00:00 [INF] - Device connected to cloud, processing subscriptions for connected clients.
```

**Comment by damonbarry** [comment]
Can you run `iotedge check --verbose` on that device and add the output here?

**Comment by somme89** [comment]
The full log from edgeHub is attached. Note that I've restarted the iotedge service a couple of times manually.

Here's the output from `iotedge check --verbose`:

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
√ DNS server - OK
‼ production readiness: certificates - Warning
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: certificates expiry - OK
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK
√ Edge Hub can bind to ports on host - OK

21 check(s) succeeded.
2 check(s) raised warnings.

Occasionally, I get an output where docker fails to resolve IoT Hub hostname which might be the source of the problem but it only happens in 1/10 tries:

√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
× container on the IoT Edge module network can connect to IoT Hub AMQP port - Error
    Container on the azure-iot-edge network could not connect to sd-prod-iot-hub.azure-devices.net:5671
        caused by: docker returned exit code: 1, stderr = Error: could not resolve Azure IoT Hub hostname: failed to lookup address information: Try again
× container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - Error
    Container on the azure-iot-edge network could not connect to sd-prod-iot-hub.azure-devices.net:443
        caused by: docker returned exit code: 1, stderr = Error: could not resolve Azure IoT Hub hostname: failed to lookup address information: Try again
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK
√ Edge Hub can bind to ports on host - OK

[edgehub.log](https://github.com/Azure/iotedge/files/3689325/edgehub.log)

**Comment by damonbarry** [comment]
I suspect the occasional problem with `iotedge check` is the same as the occasional problem with edge hub losing connectivity to its IoT hub.

You said the Linux x64 devices are identical--are you sure they all have the same versions of all OS/software components, the same settings (esp. networking), and the same hardware?

I seems like there must be some isolated hardware or software problem that is specific to this particular device...

During the ~10 minute period when this device cannot resolve your IoT hub, is it able to resolve other external addresses or is there a general inability to communicate with hosts on the internet?

**Comment by somme89** [comment]
The installation is identical to our other devices but each device is on a different network so it would be natural to suspect that the problem is in the network configuration. The device is accessed through an ssh connection that works without problems. I have been pinging www.google.com without problems for several days. All testing of DNS resolution has not shown any problems except for the `iotedge check`. 

I tried hardcoding the IP for the iothub in /etc/hosts but with no effect. However, I'm not sure if this has an effect on how the iotedge containers resolve URLs?

It is a bit of a mystery as it is only with the iotedge modules that we are experiencing problems with connectivity. Any suggestion on how to debug this problem?

**Comment by somme89** [comment]
The issue seems to have solved itself without our interaction. Connectivity has now been stable for 19 hours, but I have no idea what fixed the problem as I haven't touched the system for 2 days.

**Comment by darobs** [comment]
Hello @somme89 

If you have support, you could create an Azure Support Center ticket and provide the date and time of the trouble you were seeing. Our customer service engineers can see if there were any known problems with the service in that time frame.

**Comment by somme89** [comment]
Unfortunately, the problem is back again. I've been running various tests to pinpoint the problem but with no luck. A script has been checking DNS resolution and connectivity to EdgeHub and there has been no sign of problems for days. 

I don't think this is a problem with the Azure service as we have 20+ other devices running without any problems using the same EdgeHub. The only difference I have found in this particular device is that a public DNS service is used instead of ISP default DNS which didn't work for some reason. The public DNS server is configured using netplan and in /etc/docker/daemon.json. DNS resolution seems to be working without any problems.

**Comment by philipktlin** [comment]
Just want to clarify with your last comment.  Since you mentioned that a script is running to check DNS resolution and connectivity to EdgeHub; you are running this script inside your custom module, right? how many modules are running on the device? does this connection lost issue happen in more than 1 module? And your custom module has connection lost issue even script reports no problem, right?

Once you changed to use public DNS, does connection lost issue get resolved?

**Comment by somme89** [comment]
The script was not running inside a module so I'm not checking connectivity from inside docker only from the machine to the internet. Only one custom module is running plus edgeHub and edgeAgent. The exact same module has been deployed on 25 other machines that are set up in the same way but at different locations. It is the edgeHub module that loses connection to the Azure EdgeHub so naturally the custom module also loses connection. The script does not show any sign of connectivity issues while the edgeHub module is experiencing problems. The machine is using public DNS as there was a problem getting a DNS configuration from the router the machine is connected to. This is the only difference I have identified in the configuration compared to the other 25 deployments we have.

**Comment by philipktlin** [comment]
Please provide what OS platform/architecture you are using.

**Comment by somme89** [comment]
OS is Ubuntu LTS 18.04.2 x64

**Comment by philipktlin** [comment]
There are some issues related to netplan fixed in https://wiki.ubuntu.com/BionicBeaver/ReleaseNotes/ChangeSummary/18.04.3.  I would suggest you to upgrade to 18.04.3 version and see if this will resolve the issue.  Also it will be great if you can run your script inside EdgeHub container to log internet connection and iotedge check periodically.

**Comment by somme89** [comment]
I tried to update the system but no luck. We're now trying to install the edge services on a different machine but on the same network.

**Comment by lt72** [comment]
Hi @somme89, any new info?

**Comment by somme89** [comment]
No luck. The problem is still there. We will try to use an updated library for AMQP messaging which seems to contain some bug-fixes that are relevant. I'll post an updated once we tested it.

**Comment by somme89** [comment]
No luck with the update. We tried running `iotedge check ` for 12h every 2m which showed no problems with connectivity at all, although the edgeHub service dropped connection every ~40m as usual. Now we have another installation showing the same symptoms so it is starting to become a bigger problem. We'll test the connection from a custom module as it seems that the problem is either only present in the docker sub-network or it is not a network problem at all.

**Comment by philipktlin** [comment]
Try to run your script for checking network status inside a docker container on iotedge device; in order to confirm that the problem is about network connection inside containers only; not edgeHub or IoT Hub.  If so, we should focus to investigate why network connection inside containers is not stable.

**Comment by veyalla** [comment]
Closing since there's been no update for a while. Please re-activate if you're still blocked by this.

**Comment by somme89** [comment]
The problem is the same as in this issue: [2180](https://github.com/Azure/iotedge/issues/2180)
We'll use the newer issue to track progress.
