### ISSUE TITLE
EdgeHub Disconnect/Reconnect loop 830k d2c messages in 24h from one device

### ISSUE THREAD

**Issue by mathiash98** [Azure/iotedge#5201]
## Expected Behavior
Some timeout period should stop a device from disconnect and connect multiple times per second.

## Current Behavior
Installations with poor internet connection spam our IotHub with messages and break our max limit.
- This is forcing us to upgrade IotHub message quota in order to deploy new versions to devices. After a few days we might be able to downgrade due to vessels moving to a location with better internet connection

## Steps to Reproduce
Hard to reproduce, but a common factor is that installations have poor internet stability

## Context (Environment)
- Solution deployed on vessels around the world, where many have unstable satellite internet connection. Some have a mix of 4g and satellite.
- Usually high ping
- Some vessels often have so bad connection that VPN connection is not able to be established

### Device Information
* Ubuntu 18.04
* amd64
* Linux containers

### Output of `iotedge check` (Close to same output for all our 25 installed gateways, this is from the current mass producer of messages)

<details>
<summary>Click here</summary>

```

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Installed IoT Edge daemon has version 1.0.9.4 but 1.1.3 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 405 days (at 2022-08-14 13:25:16 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
‼ production readiness: container engine - Warning
    Device is not using a production-supported container engine (moby-engine).
    Please see https://aka.ms/iotedge-prod-checklist-moby for details.
√ production readiness: logs policy - OK
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK
17 check(s) succeeded.
6 check(s) raised warnings.

```
</details>

### Runtime Versions
* aziot-edged [run `iotedge version`]:  Mix, depends on when we installed the solution
* Edge Agent: 1.1.0 
* Edge Hub: 1.1.0
      - Seems like non of the newer updates have addressed a similar issue?
* Docker/Moby [run `docker version`]: Mix, depends on when we installed the solution

We are unfortunately unable to provide aziot-edged logs at this point due to no VPN connection.

Sadly no Edge-Agent logs either at this point

Sadly no Edge-Hub logs either at this point. 
- The logs we have seen previously have shown a large amount of connection timeout error messages on the same thread

## Additional Information
Screenshots from IotHub logs for the 2 devices we have a problem with at the moment (both are last 24hours, showing what d2c message types is sent):

Extreme case with 500k messages:
![IotEdgeDevice 1](https://user-images.githubusercontent.com/5204006/124282646-5a5ce680-db4b-11eb-9c3d-87051683dde3.png)

More usual case with around 70k messages:
![IotEdgeDevice 2](https://user-images.githubusercontent.com/5204006/124282653-5cbf4080-db4b-11eb-95ef-78354250557d.png)
- 68k device twin reads in 24h seems quite a bit high as well

A normal installation is today sending around 5k messages per day, where all of them are produced by the core IotEdge components (We do not use IotHub for sending data to cloud from onprem).

https://github.com/Azure/iotedge/pull/5188 Might be related to this issue

**Comment by jlian** [comment]
@mathiash98 can you show us screenshots for the following two metrics for the same time period?
- Total number of messages used
- Telemetry messages sent

**Comment by vipeller** [comment]
@jlian Thank you for reporting this. Yes, the referenced pull request mitigates the issue. It still lets pulling a twin in every 30 second (resulting around ~3000 twin pulls a day)

I know that a poor network can cause frequent connect/disconnect, but the numbers are really high in your case - giving almost 3 connection/sec. Is there any chance that by mistake the same connection string was used by two different devices?

**Comment by vipeller** [comment]
@jlian I used your nick accidentally for the previous comment instead of @mathiash98, sorry for the confusion

**Comment by vipeller** [comment]
@mathiash98 could you send me a mail, i'd like to organize a call to understand this problem better. my address is like my github id plus 'at microsoft dot com'. 

also, if when this happens and you check the adgeAgent logs, and it contains repeated log message starting with "Obtained Edge agent twin from IoTHub with desired properties version", then maybe there is an experimental flag that can turn off pulling the twin on reconnect, which might cause your quota filled up. In this case you would not need to wait like the above-mentioned fix gets rolled out.

**Comment by mathiash98** [comment]
> @mathiash98 could you send me a mail, i'd like to organize a call to understand this problem better. my address is like my github id plus 'at microsoft dot com'.
- I have sent you an email regarding a call :)

 
> also, if when this happens and you check the adgeAgent logs, and it contains repeated log message starting with "Obtained Edge agent twin from IoTHub with desired properties version", then maybe there is an experimental flag that can turn off pulling the twin on reconnect, which might cause your quota filled up. In this case you would not need to wait until the above-mentioned fix gets rolled out.
- Yes I see in the logs for a different installation that `Obtained Edge agent twin` log message was sent appr. 5 times per minute in the period where the computer was struggling with connection. This was in the period 2021-06-15 -> 2021-06-22. And it produced a total of 946k messages in the 7 days period. And 72k read messages in a 24h period.

What flag is this? In case we might need it again some time

**Comment by mathiash98** [comment]
> @mathiash98 can you show us screenshots for the following two metrics for the same time period?
> 
> * Total number of messages used
> * Telemetry messages sent

![image](https://user-images.githubusercontent.com/5204006/124436693-88723e80-dd76-11eb-938e-3ca5145df98f.png)
- This should be very close to the same 24h period as in my screenshots.
412k IotHub messages used
5.39k telemetry messages sent

**Comment by vipeller** [comment]
@mathiash98 did the experimental flag mitigate the issue?

**Comment by mathiash98** [comment]
> @mathiash98 did the experimental flag mitigate the issue?

Our edgeAgent was not receiving the new deployment manifest from IotHub, so I restarted it.
- This manifest did not contain the flag
Then all communications was fine and we have not experienced any large message spamming since.

So sadly we were not able to test if the flag would fix the issue. Logs from edgeAgent below:

Before edgeAgent restart:

<details>
<summary>Before edgeAgent restart</summary>
```
2021-07-08 20:52:37.290 +00:00 [INF] - Current module client closed. Initializing a new one                                                                                                                                                        
 2021-07-08 20:52:37.290 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...                                                                                                                                            
 2021-07-08 20:52:44.333 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_Tcp_Only.                                                                                                                                                          
 2021-07-08 20:52:57.574 +00:00 [INF] - Initialized new module client with subscriptions enabled                                                                                                                                                    
 2021-07-08 20:55:17.035 +00:00 [WRN] - Error getting edge agent twin from IoTHub                                                                                                                                                                   
System.TimeoutException: The operation timed out.                                                                                                                                                                                                      
 ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.                                                                                                                          
 ---> System.TimeoutException: The operation has timed out.                                                                                                                                                                                            
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.RoundTripTwinMessage(AmqpTwinMessageType amqpTwinMessageType, TwinCollection reportedProperties, CancellationToken cancellationToken)                                         
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.SendTwinGetAsync(CancellationToken cancellationToken)                                                                                                                         
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)                                                                                                                          
   --- End of inner exception stack trace ---                                                                                                                                                                                                          
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)                                                                                                                          
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass24_0.<b__0>d.MoveNext()                                                                                                                       
--- End of stack trace from previous location where exception was thrown ---                                                                                                                                                                           
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendTwinGetAsync(CancellationToken cancellationToken)                                                                                                                            
   at Microsoft.Azure.Devices.Client.InternalClient.GetTwinAsync()                                                                                                                                                                                     
   --- End of inner exception stack trace ---                                                                                                                                                                                                          
   at Microsoft.Azure.Devices.Client.InternalClient.GetTwinAsync()                                                                                                                                                                                     
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClient.GetTwinAsync() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClient.cs:line 97                                                                    
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClient.GetTwinAsync() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClient.cs:line 97                                                                    
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.<>c__DisplayClass33_0.<g__GetTwinFunc|0>d.MoveNext() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line
290                                                                                                                                                                                                                                                   
--- End of stack trace from previous location where exception was thrown ---                                                                                                                                                                           
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.GetTwinFromIoTHub(Boolean retrying) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 325                                
 2021-07-08 20:57:39.033 +00:00 [WRN] - Error getting edge agent twin from IoTHub                                                                                                                                                                   
System.TimeoutException: The operation timed out.                                                                                                                                                                                                      
 ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.                                                                                                                          
 ---> System.TimeoutException: The operation has timed out.                                                                                                                                                                                            
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.RoundTripTwinMessage(AmqpTwinMessageType amqpTwinMessageType, TwinCollection reportedProperties, CancellationToken cancellationToken)                                         
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.SendTwinGetAsync(CancellationToken cancellationToken)                                                                                                                         
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)                                                                                                                          
   --- End of inner exception stack trace ---                                                                                                                                                                                                          
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)                                                                                                                          
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass24_0.<b__0>d.MoveNext()                                                                                                                       
--- End of stack trace from previous location where exception was thrown ---                                                                                                                                                                           
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendTwinGetAsync(CancellationToken cancellationToken)                                                                                                                            
   at Microsoft.Azure.Devices.Client.InternalClient.GetTwinAsync()                                                                                                                                                                                     
   --- End of inner exception stack trace ---                                                                                                                                                                                                          
   at Microsoft.Azure.Devices.Client.InternalClient.GetTwinAsync()                                                                                                                                                                                     
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClient.GetTwinAsync() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClient.cs:line 97                                                                    
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClient.GetTwinAsync() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClient.cs:line 97                                                                    
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.<>c__DisplayClass33_0.<g__GetTwinFunc|0>d.MoveNext() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line
290                                                                                                                                                                                                                                                   
--- End of stack trace from previous location where exception was thrown ---                                                                                                                                                                           
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.GetTwinFromIoTHub(Boolean retrying) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 325                                
 2021-07-08 20:57:39.047 +00:00 [INF] - Current module client closed. Initializing a new one                                                                                                                                                        
 2021-07-08 20:57:39.047 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...                                                                                                                                            
 2021-07-08 20:57:46.084 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_Tcp_Only.                                                                                                                                                          
 2021-07-08 20:59:08.080 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...                                                                                                                                            
 2021-07-08 20:59:08.080 +00:00 [WRN] - Error handling module client closed event                                                                                                                                                                   
System.TimeoutException: The operation timed out.                                                                                                                                                                                                      
 ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: The operation did not complete within the allocated time 00:01:00 for object receiver18775668.   

(….)


2021-07-08 21:06:36.122 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_Tcp_Only.                                                                                                                                                          
 2021-07-08 21:07:09.991 +00:00 [WRN] - Error getting edge agent twin from IoTHub                                                                                                                                                                   
Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Amqp resource is disconnected.                                                                                                                                                 
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSession.OpenReceivingAmqpLinkAsync(DeviceIdentity deviceIdentity, AmqpSession amqpSession, Nullable`1 senderSettleMode, Nullable`1 receiverSettleMode, String deviceTemplate, String modu
leTemplate, String linkSuffix, String correlationId, TimeSpan timeout)                                                                                                                                                                                 
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSession.OpenTwinReceiverLinkAsync(DeviceIdentity deviceIdentity, String correlationIdSuffix, TimeSpan timeout)                                                                           
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenTwinReceiverLinkAsync(AmqpIoTSession amqpIoTSession, String correlationIdSuffix, TimeSpan timeout)                                                                                 
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnableTwinLinksAsync(TimeSpan timeout)                                                                                                                                                 
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.EnableTwinPatchAsync(CancellationToken cancellationToken)                                                                                                                     
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<b__0>d.MoveNext()                                                                                                          
--- End of stack trace from previous location where exception was thrown ---                                                                                                                                                                           
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)                                                                                                                          
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass23_0.<b__0>d.MoveNext()                                                                                                                   
--- End of stack trace from previous location where exception was thrown ---                                                                                                                                                                           
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnableTwinPatchAsync(CancellationToken cancellationToken)                                                                                                                        
   at Microsoft.Azure.Devices.Client.InternalClient.SetDesiredPropertyUpdateCallbackAsync(DesiredPropertyUpdateCallback callback, Object userContext, CancellationToken cancellationToken)                                                             
   at Microsoft.Azure.Devices.Client.InternalClient.SetDesiredPropertyUpdateCallbackAsync(DesiredPropertyUpdateCallback callback, Object userContext)                                                                                                  
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClient.SetDesiredPropertyUpdateCallbackAsync(DesiredPropertyUpdateCallback onDesiredPropertyChanged) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClient
.cs:line 55                                                                                                                                                                                                                                            
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClient.SetDesiredPropertyUpdateCallbackAsync(DesiredPropertyUpdateCallback onDesiredPropertyChanged) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClient
.cs:line 55                                                                                                                                                                                                                                            
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleConnection.b__11_1() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleConnection.cs:line 84                                               
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleConnection.InitModuleClient() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleConnection.cs:line 87                                                        
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleConnection.GetOrCreateModuleClient() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleConnection.cs:line 50                                                 
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.<>c__DisplayClass33_0.<g__GetTwinFunc|0>d.MoveNext() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line
290                                                                                                                                                                                                                                                   
--- End of stack trace from previous location where exception was thrown ---                                                                                                                                                                           
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.GetTwinFromIoTHub(Boolean retrying) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 325                                
 2021-07-08 21:07:09.999 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...                                                                                                                                            
 2021-07-08 21:07:17.060 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_Tcp_Only.                                                                                                                                                          
 2021-07-08 21:07:36.041 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...                                                                                                                                            
 2021-07-08 21:07:42.920 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_Tcp_Only.                                                                                                                                                          
 2021-07-08 21:07:54.365 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...                                                                                                                                            
 2021-07-08 21:08:01.243 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_Tcp_Only.                                                                                                                                                          
 2021-07-08 21:09:39.923 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...                                                                                                                                            
 2021-07-08 21:09:46.832 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_Tcp_Only.                                                                                                                                                          
 2021-07-08 21:10:51.913 +00:00 [WRN] - Error getting edge agent twin from IoTHub                                                                                                                                                                   
System.TimeoutException: The operation timed out.

```
</details>

After edgeAgent restart:
<details>
<summary>After edgeAgent restart</summary>
```
2021-07-09 07:05:36.582 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false}                                                                                                                    
 2021-07-09 07:05:37.048 +00:00 [INF] - Installing certificates [CN=Test Edge Owner CA:08/14/2022 13:25:16] to Root                                                                                                                                 
 2021-07-09 07:05:37.448 +00:00 [INF] - Starting metrics listener on Host: *, Port: 9600, Suffix: /metrics                                                                                                                                          
 2021-07-09 07:05:37.914 +00:00 [INF] - Updating performance metrics every 05m:00s                                                                                                                                                                  
 2021-07-09 07:05:37.927 +00:00 [INF] - Started operation Get system resources                                                                                                                                                                      
 2021-07-09 07:05:37.932 +00:00 [INF] - Collecting metadata metrics                                                                                                                                                                                 
 2021-07-09 07:05:38.269 +00:00 [INF] - Set metadata metrics: 1.1.0.39334128 (92ac4878a4c8ca74c0db14cd2e63273f1c8661f4), {"Enabled":false,"DisableCloudSubscriptions":false}, {"OperatingSystemType":"linux","Architecture":"x86_64","Version":"1.0.
9.4","Provisioning":{"Type":"","DynamicReprovisioning":false},"ServerVersion":"","KernelVersion":"","OperatingSystem":"","NumCpus":0,"Virtualized":""}, True                                                                                           
 2021-07-09 07:05:38.336 +00:00 [INF] - Started operation Checkpoint Availability                                                                                                                                                                   
 2021-07-09 07:05:38.346 +00:00 [INF] - Started operation refresh twin config                                                                                                                                                                       
 2021-07-09 07:05:38.406 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...                                                                                                                                            
 2021-07-09 07:05:39.820 +00:00 [INF] - Created persistent store at /tmp/edgeAgent                                                                                                                                                                  
 2021-07-09 07:05:40.041 +00:00 [INF] - Started operation Metrics Scrape                                                                                                                                                                            
 2021-07-09 07:05:40.042 +00:00 [INF] - Started operation Metrics Upload                                                                                                                                                                            
Scraping frequency: 01:00:00                                                                                                                                                                                                                           
Upload Frequency: 1.00:00:00                                                                                                                                                                                                                           
 2021-07-09 07:05:40.718 +00:00 [INF] - Registering request handler UploadModuleLogs                                                                                                                                                                
 2021-07-09 07:05:40.718 +00:00 [INF] - Registering request handler GetModuleLogs                                                                                                                                                                   
 2021-07-09 07:05:40.719 +00:00 [INF] - Registering request handler UploadSupportBundle                                                                                                                                                             
 2021-07-09 07:05:40.719 +00:00 [INF] - Registering request handler RestartModule                                                                                                                                                                   
 2021-07-09 07:05:46.532 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead                                                                                            
 2021-07-09 07:05:46.735 +00:00 [INF] - Obtained edge agent config from backup config file - /tmp/edgeAgent/backup.json                                                                                                                             
 2021-07-09 07:05:46.867 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_Tcp_Only.                                                                                                                                                          
 2021-07-09 07:05:47.223 +00:00 [INF] - Plan execution started for deployment 28                                                                                                                                                                    
 2021-07-09 07:05:47.232 +00:00 [INF] - Executing command: "Command Group: (\n  [Stop module fw]\n  [Start module fw]\n  [Saving fw to store]\n)"                                                                                                   
 2021-07-09 07:05:47.244 +00:00 [INF] - Executing command: "Stop module fw"                                                                                                                                                                         
 2021-07-09 07:05:47.297 +00:00 [INF] - Executing command: "Start module fw"                                                                      

```
</details>

- Logs in azure also indicate that the issue stopped after restarting edgeAgent

**Comment by mathiash98** [comment]
Can confirm that this issue is still occuring on seemingly random installations.
Last 2 weeks we have had the issue on 3 installations running EdgeAgent 1.1.0

Logs are stilling spewing out `Obtained Edge agent twin from IotHub with desired properties version xx and reported properties yyy` with 300ms timeout between each message.


![image](https://user-images.githubusercontent.com/5204006/133963498-881061d9-1da1-4ae3-83df-8d10a0e89434.png)
- Number of iot messages per 60m for all our installations

**Comment by SondreNjaastad** [comment]
Hi! We are experiencing the same issue. Its somewhat rare, but it have happened 2 times the last year (The first time we didnt find the actual source, but its very likely the same issue.) This time we dug into it.

A device that had been deployed for a long time suddently started spamming D2C messages. I took out the logs and averaged the messages over time to;

1,395,392 times over 47 hours, thats 8.08 messages/second
And looking at the time between each  message for around 1M messages, the average was 120ms.

Needless to say, our IoTHub quota was exceeded within a very short time, and the messages from other devices stopped as a result. This kept on over the weekend, but solved itself before we got to work on monday.

**Comment by vipeller** [comment]
Hi, we found the actual bug causing this in egdeAgent and the latest versions on both 1.1 and 1.2 should have the fix released.

**Comment by mathiash98** [comment]
> Hi, we found the actual bug causing this in egdeAgent and the latest versions on both 1.1 and 1.2 should have the fix released.

Not sure if coincident or another issue or still same issue, but right after we depoloyed edgeAgent and edgeHub 1.1.8 we experienced the same kind of high message sending (in much smaller scale):

![image](https://user-images.githubusercontent.com/5204006/146342456-f6e072bf-0812-47f7-808c-531da064bc71.png)
- Deplyoed 15-30min before the graph spiked.
- Computer was down in the low area to the right.
- After restart: sent a spike of messages
- Then calmed down 

![image](https://user-images.githubusercontent.com/5204006/146343947-2521301f-7e07-4c8f-a498-2c0b3c45d6e1.png)
- Now we are talking about update operations.
- Image shows data from Dec 14 09:21 UTC to Dec 15 09:21 UTC

**Comment by vipeller** [comment]
Hi @mathiash98, thanks for reporting this! I think it is a different problem and from the second log it seems that agent was not able to deploy something and kept retrying every 5sec - although it strange that there no related error message.

Coincidently I am looking at the exact same code piece for other reasons (agent and its retry logic when something fails) - in that case if a user accidentally defines a nonexisting image for a module, agent has the same retry logic (every 5 second), but the difference is that we see the related error. Anyway, because by the retry docker starts talking to the registry, it opens a tls connection (just this causes ~4kb to download), asks for the image every 5 secs, altogether it generates significant traffic.

I believe there is something similar is going on in your case (not a bad image definition but something else preventing a good deployment). Maybe because of this, edgeAgent reports back something to iothub, that gives the message number you see.

Let me spend some time analyzing this part of the code, then I come back with some more explanation what may cause this. Also, agent is supposed to have an exponential retry logic, so most probably a fix will come out to eliminate the constant 5 sec tries in cases like this.

**Comment by mathiash98** [comment]
Hi @vipeller, You are completely right. I checked again and saw that we had a layered deployment trying to download a nonexisting containerImage. This has now been removed. We will try again with 1.1.8 after we have released our goal this month

**Comment by mathiash98** [comment]
Hello it's been a while, and I have not thought much about this issue as we release less frequently and have increased the message limit in IotHub.

But I can confirm that this is still an issue on Edge(Agent/Hub) 1.4.6
Clouse to all of our installations are running IotEdge 1.1.1x together with EdgeAgent & EdgeHub on 1.4.6
- new installations will have IotEdge 1.4 using `apt-get install aziot-edge defender-iot-micro-agent-edge -y` while the old ones, including those that report more than 1000 messages per hour are running the old method with `apt-get install iotedge -y`

![image](https://user-images.githubusercontent.com/5204006/221892144-71765d77-388f-4d28-b2db-0006fc44f3c7.png)

**Comment by mathiash98** [comment]
The issue seems to be resolved somewhere between EdgeAgent/EdgeHub 1.4.6 and 1.4.10
- We released an update 24. may that resulted in fetching latest EdgeAgent
![Screenshot 2023-05-26 at 10 06 00](https://github.com/Azure/iotedge/assets/5204006/f69d5422-cb7e-419b-93c2-d6a5b68bbfc0)
