### ISSUE TITLE
IoTEdgeHub module client cannot connect unless network is set to "azure-iot-edge"

### ISSUE THREAD

**Issue by Strandfelt** [Azure/iotedge#820]
I have had an issue with IoT Edge on Windows with Windows Containers that really confused me, since there was no help in the documentation for Windows containers, however, a suggestion for Linux containers turned out to be the solution.

## Expected Behavior
The IoT Edge OPC Publisher should be able to initialize IoTEdgeHub module client connection

## Current Behavior
Connection fails with `Connection status changed to 'Disconnected', reason 'Retry_Expired'`

## Steps to Reproduce

1. Install IoT Edge
2. Follow IoT Edge OPC Publisher module steps [here](https://github.com/Azure/iot-edge-opc-publisher#using-it-as-a-module-in-azure-iot-edge). Use version `2.3.1` (currently the latest)
3. Start IoT Edge
4. Note that the OPC Publisher cannot connect to the Edge Hub
5. Stop IoT Edge
6. Edit `C:\ProgramData\iotedge\config.yaml` and change `moby_runtime:` `network` from `'nat'` to  `'azure-iot-edge'`
7. Start IoT Edge
8. Notice how OPC Publisher now connects

### Device (Host) Operating System
Windows 10 Pro Version 1809 (10.0.17763.292)

### Architecture
64-bit

### Container Operating System
Windows Containers

#### iotedged
iotedge 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)

#### Edge Agent
mcr.microsoft.com/azureiotedge-agent:1.0

#### Edge Hub
mcr.microsoft.com/azureiotedge-hub:1.0.6

#### Docker
```Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:34:26 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:50:10 2019
  OS/Arch:          windows/amd64
  Experimental:     false
```

## Logs
```
[10:54:28 INF] Current directory is: C:\appdata
[10:54:28 INF] Log file is: publisher-publisher.log
[10:54:28 INF] Log level is: info
[10:54:28 INF] OPC Publisher V2.3.1 starting up...
[10:54:28 INF] opcstacktracemask set to: 0x0
[10:54:28 INF] OperationTimeout set to 120000
[10:54:28 INF] OPC UA server base address: opc.tcp://publisher:62222/UA/Publisher
[10:54:28 INF] Security policy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256 with mode SignAndEncrypt added
[10:54:28 INF] Trusted Issuer store type is: Directory
[10:54:28 INF] Trusted Issuer Certificate store path is: pki/issuer
[10:54:28 INF] Trusted Peer Certificate store type is: Directory
[10:54:28 INF] Trusted Peer Certificate store path is: pki/trusted
[10:54:28 INF] Rejected certificate store type is: Directory
[10:54:28 INF] Rejected Certificate store path is: pki/rejected
[10:54:28 INF] Rejection of SHA1 signed certificates is disabled
[10:54:28 INF] Minimum certificate key size set to 1024
[10:54:28 INF] Application Certificate store type is: Directory
[10:54:28 INF] Application Certificate store path is: pki/own
[10:54:28 INF] Application Certificate subject name is: publisher
[10:54:28 WRN] WARNING: Automatically accepting certificates. This is a security risk.
[10:54:28 INF] Application certificate with thumbprint '5CE4A5C395A8297C6CDF27EF34FE6186288048A4' found in the application certificate store.
[10:54:28 INF] Application certificate is for ApplicationUri 'urn:publisher:publisher:microsoft:', ApplicationName 'publisher' and Subject is 'publisher'
[10:54:28 INF] Adding server certificate to trusted peer store. StorePath=pki/trusted
[10:54:28 WRN] Can not add server certificate to trusted peer store. Maybe it is already there.
System.ArgumentException: A certificate with the same thumbprint is already in the store.
   at Opc.Ua.DirectoryCertificateStore.Add(X509Certificate2 certificate, String password)
   at OpcPublisher.OpcApplicationConfiguration.InitApplicationSecurityAsync() in C:\app\opcpublisher\OpcApplicationConfigurationSecurity.cs:line 241
[10:54:28 INF] LDS(-ME) registration intervall set to 0 ms (0 means no registration)
[10:54:28 INF] Trusted issuer store contains 0 certs
[10:54:28 INF] Trusted issuer store has 0 CRLs.
[10:54:28 INF] Trusted peer store contains 1 certs
[10:54:28 INF] 01: Subject 'CN=publisher' (thumbprint: 5CE4A5C395A8297C6CDF27EF34FE6186288048A4)
[10:54:28 INF] Trusted peer store has 0 CRLs.
[10:54:28 INF] Rejected certificate store contains 0 certs
[10:54:28 INF] There is no site configured.
[10:54:28 INF] Starting server on endpoint opc.tcp://publisher:62222/UA/Publisher ...
[10:54:29 INF] Server started.
[10:54:29 INF] Using default telemetry configuration.
[10:54:29 INF] The name of the configuration file for published nodes is: ./pn.json
[10:54:29 INF] Attemtping to load node configuration from: ./pn.json
[10:54:29 INF] Loaded 0 config file entry/entries.
[10:54:29 INF] There are 0 nodes to publish.
[10:54:29 INF] Create IoTEdgeHub module client using 'Mqtt_Tcp_Only' for communication.
[10:54:29 INF] IoTCentral mode: False
[10:54:31 ERR] Connection status changed to 'Disconnected', reason 'Retry_Expired'
```

**Comment by sebader** [comment]
You could try to change the transport protocol from MQTT to AMQP. This should resolve the behavior in my experience. 
@hansgschossmann is this configurable?

**Comment by Strandfelt** [comment]
@sebader I am doing it, because if I don't, the OPC Publisher fails creating a client towards the Edge Hub module. If I do a fresh install on a new PC and don't change the 'nat' value to 'azure-iot-edge', the connection fails as displayed in the log.

**Comment by bjaben** [comment]
Hi @Strandfelt
Quick question: why did you change the value to 'azure-iot-edge'? Did you create a docker bridge network with that name?
The reason I'm asking is that I have the same Environment as you and I'm getting the same error after following the IoT Edge OPC Publisher module steps. **But** changing the network from 'nat' to 'azure-iot-edge' does not solve it for me.

Can you provide some insight into your solution environment? Thanks!

**Comment by lt72** [comment]
Closing this issue as it seems stale. Please re-open as needed.
